### PR TITLE
KEP-97: Merge KEP-97-bugfix to devel

### PR DESCRIPTION
**Pull request by scottburch**

### CODE REVIEW

**Comment by dmitrymukhin** [comment]
@rnistuk  Hey Rich please review!

**Comment by rnistuk** [comment]
- the problem that this was supposed to fix went away on the Ropstein side. Dmitry is going to put the toke in an environment variable...

**Comment by rnistuk** [comment]
We're going to handle this problem a bit differently. Closing this issue without rebasing.

**Comment by dmitrymukhin** [comment]
API token pulled from ETHERSCAN_IO_API_TOKEN envar. (Add line to /etc/environment) like
ETHERSCAN_IO_API_TOKEN=53IW57FSZSZS3QXJUEBYT8F4YZ9IZFXBP

**Pull request closed without merging**
